In [27]:
import pandas as pd
df=pd.read_csv("iris.csv")

In [28]:
df1=df
df.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa

In [29]:
df1.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa

In [30]:
df.loc[0,"Sepal.length"]=34
df.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety  Sepal.length
0           5.1          3.5           1.4          0.2  Setosa          34.0
1           4.9          3.0           1.4          0.2  Setosa           NaN

In [31]:
df1.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety  Sepal.length
0           5.1          3.5           1.4          0.2  Setosa          34.0
1           4.9          3.0           1.4          0.2  Setosa           NaN

In [32]:
df2=df.copy(deep=True)
df2.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety  Sepal.length
0           5.1          3.5           1.4          0.2  Setosa          34.0
1           4.9          3.0           1.4          0.2  Setosa           NaN

In [33]:
df.loc[1,"petal.length"]=2.8
df.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety  Sepal.length
0           5.1          3.5           1.4          0.2  Setosa          34.0
1           4.9          3.0           2.8          0.2  Setosa           NaN

In [34]:
df2.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety  Sepal.length
0           5.1          3.5           1.4          0.2  Setosa          34.0
1           4.9          3.0           1.4          0.2  Setosa           NaN

In [35]:
df3=df.copy(deep=False)
df3.head(3)

   sepal.length  sepal.width  petal.length  petal.width variety  Sepal.length
0           5.1          3.5           1.4          0.2  Setosa          34.0
1           4.9          3.0           2.8          0.2  Setosa           NaN
2           4.7          3.2           1.3          0.2  Setosa           NaN

In [36]:
df.loc[0,"Sepal.width"]=7
df3.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety  Sepal.length
0           5.1          3.5           1.4          0.2  Setosa          34.0
1           4.9          3.0           2.8          0.2  Setosa           NaN

In [37]:
df3.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety  Sepal.length
0           5.1          3.5           1.4          0.2  Setosa          34.0
1           4.9          3.0           2.8          0.2  Setosa           NaN

In [38]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Store' : ['A','B','A','C','B','A'],
    'Product' : ['Laptop','Mouse','Tablet','Laptop','Mouse','Tablet'],
    'Sales' : [1000, 50, 300, 1200, 60, 350],
    'Quantity' : [5, 10, 3, 6, 8, 4]
})
print(df)

  Store Product  Sales  Quantity
0     A  Laptop   1000         5
1     B   Mouse     50        10
2     A  Tablet    300         3
3     C  Laptop   1200         6
4     B   Mouse     60         8
5     A  Tablet    350         4

In [44]:
print(df["Sales"].sum())
print(df["Sales"].mean())
print(df["Sales"].count())
print(df["Sales"].median())
print(df["Sales"].std())

2960
493.3333333333333
6
325.0
489.5576234384127

In [49]:
df["Sales"].agg(["sum","std","mean","count","median"])

sum       2960.000000
std        489.557623
mean       493.333333
count        6.000000
median     325.000000
Name: Sales, dtype: float64

In [51]:
pd.DataFrame(df.groupby("Store"))

   0                                                  1
0  A    Store Product  Sales  Quantity
0     A  Lapt...
1  B    Store Product  Sales  Quantity
1     B   Mou...
2  C    Store Product  Sales  Quantity
3     C  Lapt...

In [54]:
df.groupby("Store")["Sales"].sum()

Store
A    1650
B     110
C    1200
Name: Sales, dtype: int64

In [55]:
print(df.groupby("Store")["Sales"].sum())
print(df.groupby("Store")["Sales"].mean())
print(df.groupby("Store")["Sales"].std())
print(df.groupby("Store")["Sales"].count())

Store
A    1650
B     110
C    1200
Name: Sales, dtype: int64
Store
A     550.0
B      55.0
C    1200.0
Name: Sales, dtype: float64
Store
A    390.512484
B      7.071068
C           NaN
Name: Sales, dtype: float64
Store
A    3
B    2
C    1
Name: Sales, dtype: int64

In [56]:
df.groupby("Store")["Sales"].agg(["sum","std","mean","count","median"])

        sum         std    mean  count  median
Store
A      1650  390.512484   550.0      3   350.0
B       110    7.071068    55.0      2    55.0
C      1200         NaN  1200.0      1  1200.0

In [57]:
df.groupby("Store")["Quantity"].agg(["sum","std","mean","count","median"])

       sum       std  mean  count  median
Store
A       12  1.000000   4.0      3     4.0
B       18  1.414214   9.0      2     9.0
C        6       NaN   6.0      1     6.0

In [61]:
df.columns
pd.DataFrame(df.groupby(["Store","Product"]))

             0                                                  1
0  (A, Laptop)    Store Product  Sales  Quantity
0     A  Lapt...
1  (A, Tablet)    Store Product  Sales  Quantity
2     A  Tabl...
2   (B, Mouse)    Store Product  Sales  Quantity
1     B   Mou...
3  (C, Laptop)    Store Product  Sales  Quantity
3     C  Lapt...

In [63]:
df.columns
df.groupby(["Store","Product"])["Sales"].agg(["sum","mean","std"])

                sum    mean        std
Store Product
A     Laptop   1000  1000.0        NaN
      Tablet    650   325.0  35.355339
B     Mouse     110    55.0   7.071068
C     Laptop   1200  1200.0        NaN